name: WSI_preprocessing
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - h5py==3.11.0
  - matplotlib==3.8.3
  - numpy==1.26.4
  - opencv-python==4.8.0.76
  - opencv-python-headless==4.9.0.80
  - openslide-python==1.3.1
  - pandas==2.2.2
  - pillow==10.3.0
  - setuptools==69.2.0
  - scikit-image==0.18.3
  - torch==2.1.2
  - torchvision==0.16.2
