# input/output
    input_path: /mnt/c/Users/loren/Downloads/Camelyon16/images/normal_001.tif # path to input file/directory
    output_path: /mnt/c/Users/loren/Downloads/Camelyon16/preprocessing5/  # path to output directory
    
    # tile customization
    desired_size: 256  # Desired size of the tiles
    desired_magnification: 20  # Desired magnification level
    overlap: 1  # Overlap between tiles
    
    # preprocessing processes customization
    remove_blurry_tiles: true  # flag to enable usage of the laplacian filter to remove blurry tiles
    normalize_staining: true  # Flag to enable normalization of tiles
    encode: false  # Flag to encode tiles and create associated .h5 file
    reconstruct_slide: false  # reconstruct slide

    output_format: h5  # reconstruct slide

    # encoding customizations
    extract_high_quality: false  # extract high quality
    augmentations: 0  # augment data for training
    encoder_model: resnet50  # current options: resnet50, mahmood-uni
    token: null  # required to download model weights from hugging face
    
    # thresholds 
    tissue_threshold: 0.7  # Threshold to consider a tile as Tissue
    blur_threshold: 0.015  # Threshold for laplace filter variance
    red_pen_check: 0.4  # Sanity check for % of red pen detected. If above threshold, red_pen mask will be ignored
    blue_pen_check: 0.4  # Sanity check for % of blue pen detected, If above threshold, blue_pen mask will be ignored
    include_adipose_tissue: false  # will include adipose tissue in mask
    remove_folds: false  # will remove folded tissue in mask
    mask_scale: 64  # scale at which to downscale WSI for masking. Recommended is either 64 or None which will downsize to the lowest possible downscale recommended by openslide. None will produce a higher quality mask but is slower than 64
    
    # for devices + multithreading
    device: null  # device to use (e.g., 'cuda:0', 'cpu')
    gpu_processes: 1  # number of GPU processes
    cpu_processes: null  # number of CPU processes, if null
    batch_size: 16  # batch size for processing
    
    # QC 
    min_tiles: 0  # Number of tiles a patient should have
    